CREATE TABLE utente (
    codiceutente INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    username     VARCHAR(30)  NOT NULL,
    email        VARCHAR(100) NOT NULL,
    password     VARCHAR(100) NOT NULL,
    nome         VARCHAR(50)  NOT NULL,
    cognome      VARCHAR(50)  NOT NULL,

    CONSTRAINT pkutente          PRIMARY KEY (codiceutente),
    CONSTRAINT ckusernameunivoco UNIQUE (username),
    CONSTRAINT ckemailunivoca    UNIQUE (email),
    CONSTRAINT ckemailnotnull    CHECK (email IS NOT NULL),
    CONSTRAINT ckemailformato    CHECK (email LIKE '%_@_%._%')
);


CREATE TABLE elementomultimediale (
    id_elemento       INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    titolo            VARCHAR(150) NOT NULL,
    durata            INTEGER      NOT NULL,
    descrizione       TEXT,
    testo             TEXT,
    datacreazione     DATE         NOT NULL DEFAULT CURRENT_DATE,
    immaginecopertina VARCHAR(255),
    tipomedia         VARCHAR(5)   NOT NULL,
    bitrate           INTEGER,
    formato           VARCHAR(10),
    codec             VARCHAR(20),
    framerate         INTEGER,
    risoluzione       VARCHAR(15),
    codiceutente      INTEGER      NOT NULL,

    CONSTRAINT pkelementomultimediale PRIMARY KEY (id_elemento),
    CONSTRAINT fkelementoautore FOREIGN KEY (codiceutente)
        REFERENCES utente (codiceutente) ON DELETE CASCADE,
    CONSTRAINT ckelementotipomedia CHECK (tipomedia IN ('Audio', 'Video')),
    CONSTRAINT ckduratapositiva    CHECK (durata > 0),
    CONSTRAINT ckelementoattrtipomedia CHECK (
        (tipomedia = 'Audio'
             AND bitrate   IS NOT NULL AND formato     IS NOT NULL AND codec IS NOT NULL
             AND framerate IS NULL     AND risoluzione IS NULL)
     OR (tipomedia = 'Video'
             AND framerate IS NOT NULL AND risoluzione IS NOT NULL
             AND bitrate   IS NULL     AND formato     IS NULL     AND codec IS NULL)
    )
);


CREATE TABLE statisticheriproduzione (
    id_elemento        INTEGER NOT NULL,
    numeroascolti      INTEGER NOT NULL DEFAULT 0,
    numerocondivisioni INTEGER NOT NULL DEFAULT 0,
    mipiace            INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT pkstatisticheriproduzione PRIMARY KEY (id_elemento),
    CONSTRAINT fkstatisticheelemento FOREIGN KEY (id_elemento)
        REFERENCES elementomultimediale (id_elemento) ON DELETE CASCADE,
    CONSTRAINT ckstatistichenonnegative
        CHECK (numeroascolti >= 0 AND numerocondivisioni >= 0 AND mipiace >= 0)
);

CREATE TABLE playlist (
    id_playlist   INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR(100) NOT NULL,
    datacreazione DATE         NOT NULL DEFAULT CURRENT_DATE,
    numerobrani   INTEGER      NOT NULL DEFAULT 0,
    copertina     VARCHAR(255),
    ispubblica    BOOLEAN      NOT NULL DEFAULT FALSE,
    iscondivisa   BOOLEAN      NOT NULL DEFAULT FALSE,
    isprivata     BOOLEAN      NOT NULL DEFAULT TRUE,
    tagricerca    VARCHAR(200),
    codiceutente  INTEGER      NOT NULL,

    CONSTRAINT pkplaylist PRIMARY KEY (id_playlist),
    CONSTRAINT fkplaylistcreatore FOREIGN KEY (codiceutente)
        REFERENCES utente (codiceutente) ON DELETE CASCADE,
    
    CONSTRAINT ckplaylistvisibilita CHECK (
        (ispubblica::int + iscondivisa::int + isprivata::int) = 1
    ),
 
    CONSTRAINT ckplaylistattrvisibilita CHECK (
        NOT ispubblica OR tagricerca IS NOT NULL
    ),
    CONSTRAINT cknumerobraninonnegativo CHECK (numerobrani >= 0),
    CONSTRAINT ckplaylistnomeunico UNIQUE (codiceutente, nome)
);


CREATE TABLE includeelemento (
    id_playlist INTEGER NOT NULL,
    id_elemento INTEGER NOT NULL,

    CONSTRAINT pkincludeelemento PRIMARY KEY (id_playlist, id_elemento),
    CONSTRAINT fkincludeplaylist FOREIGN KEY (id_playlist)
        REFERENCES playlist (id_playlist) ON DELETE CASCADE,
    CONSTRAINT fkincludeelemento FOREIGN KEY (id_elemento)
        REFERENCES elementomultimediale (id_elemento) ON DELETE CASCADE
);


CREATE TABLE condivisione (
    codiceutente      INTEGER      NOT NULL,
    id_playlist       INTEGER      NOT NULL,
    linkcondivisione  VARCHAR(255) NOT NULL,
    condivisioneamico BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT pkcondivisione PRIMARY KEY (codiceutente, id_playlist),
    CONSTRAINT fkcondivisioneutente FOREIGN KEY (codiceutente)
        REFERENCES utente (codiceutente) ON DELETE CASCADE,
    CONSTRAINT fkcondivisioneplaylist FOREIGN KEY (id_playlist)
        REFERENCES playlist (id_playlist) ON DELETE CASCADE,
    CONSTRAINT ckcondivisionelink CHECK (
        linkcondivisione IS NOT NULL AND length(trim(linkcondivisione)) > 0
    )
);


CREATE TABLE amicizia (
    codiceutente1 INTEGER NOT NULL,
    codiceutente2 INTEGER NOT NULL,

    CONSTRAINT pkamicizia PRIMARY KEY (codiceutente1, codiceutente2),
    CONSTRAINT fkamicizia1 FOREIGN KEY (codiceutente1)
        REFERENCES utente (codiceutente) ON DELETE CASCADE,
    CONSTRAINT fkamicizia2 FOREIGN KEY (codiceutente2)
        REFERENCES utente (codiceutente) ON DELETE CASCADE,
    CONSTRAINT ckamicizianonriflessiva CHECK (codiceutente1 < codiceutente2)
);
